# Generated by Django 2.0 on 2018-03-03 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rsm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('courseName', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='userExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='server',
            name='id',
        ),
        migrations.AlterField(
            model_name='server',
            name='hostIP',
            field=models.GenericIPAddressField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='hostName',
            field=models.CharField(default='No Name', max_length=20),
        ),
        migrations.AlterField(
            model_name='server',
            name='hostPort',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='server',
            name='hostUser',
            field=models.CharField(default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='userext',
            name='serverNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rsm.server'),
        ),
        migrations.AddField(
            model_name='userext',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
