# Generated by Django 2.0 on 2018-03-03 03:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rsm', '0002_auto_20180303_0311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userExt',
            new_name='profile',
        ),
    ]
