# Generated by Django 2.0 on 2018-03-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm', '0003_auto_20180303_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='hostUser',
        ),
        migrations.AlterField(
            model_name='server',
            name='hostIP',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='server',
            name='hostName',
            field=models.CharField(default='No Name', max_length=20, primary_key=True, serialize=False),
        ),
    ]
