# Generated by Django 2.0 on 2018-03-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm', '0004_auto_20180308_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='serverNum',
        ),
        migrations.AddField(
            model_name='profile',
            name='serverNum',
            field=models.ManyToManyField(to='rsm.server'),
        ),
    ]
