# Generated by Django 2.0 on 2018-03-08 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsm', '0005_auto_20180308_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='serverNum',
        ),
        migrations.AddField(
            model_name='profile',
            name='serverNum',
            field=models.ForeignKey(default='no server', on_delete=django.db.models.deletion.DO_NOTHING, to='rsm.server'),
            preserve_default=False,
        ),
    ]
