# Generated by Django 2.0 on 2018-03-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm', '0006_auto_20180308_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='serverNum',
            field=models.CharField(default='[]', max_length=10000),
        ),
    ]
