# Generated by Django 2.0 on 2018-03-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm', '0007_auto_20180308_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='robotConnected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='robotNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='serverNum',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
