# Generated by Django 2.0 on 2018-03-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsm', '0008_auto_20180315_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='robotConnected',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='robotNo',
        ),
    ]
