# Generated by Django 2.0 on 2018-04-07 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rsm.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rsm', '0009_auto_20180315_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='default.txt', upload_to=rsm.models.upload_to)),
                ('belongTo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
