# Generated by Django 2.0 on 2018-04-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm', '0010_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='targetContainer',
            field=models.CharField(default='server0', max_length=20),
        ),
    ]
