# Generated by Django 2.0 on 2018-05-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm', '0011_uploadfile_targetcontainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='category',
            field=models.CharField(choices=[('Indigo', 'Indigo'), ('Kinetic', 'Kinetic'), ('Lunar', 'Lunar'), ('Linux14', 'Linux14'), ('Linux16', 'Linux16')], default='Linux16', max_length=10),
        ),
    ]
